### ISSUE TITLE
Complete fix for WebKit browsers

### ISSUE THREAD

**Issue by meezaan** [islamic-network/alquran-tools#1]

**Comment by meezaan** [comment]
In progress in 'mapper' branch.

**Comment by husayt** [comment]
This is about to be resolved as chrome is  switching to new rendering engine [LayoutNg](https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/core/layout/ng/README.md) which solves most of the [RTL issues](https://developers.google.com/web/updates/2019/06/layoutNG). I will test it and share some of my foundings here.

**Comment by meezaan** [comment]
This appears to have been resolved now. On Chrome version 77.0.3865.90 the text renders fine on https://alquran.cloud/tajweed-guide.

I'm closing the issue unless anyone can reproduce on a version newer than the one above.
