### ISSUE TITLE
How to use Tajweed in React or Javascript

### ISSUE THREAD

**Issue by aamirbhat382** [islamic-network/alquran-tools#11]
_How to use Tajweed in React or Javascript_
I want to use Tajweed in React app, but how? or I write a custom code for that, it's not hard for me but the logic in Ayah which I am getting from API is hard for me to understand

**Comment by meezaan** [comment]
Al Salaamu Alaykum.

You'll need to create an equivalent of https://github.com/islamic-network/alquran-tools/blob/master/src/AlQuranCloud/Tools/Parser/Tajweed.php in JavaScript for this to happen.

**Comment by aamirbhat382** [comment]
I have Published npm Package for that, [View Package  ](https://github.com/aamirbhat382/Tajweed)
```
npm I tajweed
```
