### ISSUE TITLE
What do numbers mean in some meta?

### ISSUE THREAD

**Issue by vipafattal** [islamic-network/alquran-tools#9]
There are some cases that have next to the meta some numbers, what are they representing? Is it OK if just ignored them?

**Comment by meezaan** [comment]
Al Salaamu Alaykum.

I assume you are talking about the quran-wordbyword edition?

I honest do not know what they mean, they came with the data. You can safely ignore them as far as rendering the text is concerned.

You can also use the quran-wordbyword-2 edition.

**Comment by vipafattal** [comment]
Sorry I was talking about the number quran-tajweed edition.

There are some metas have numbers next to them such as [h:9431].

**Comment by meezaan** [comment]
Yes, these can be ignored. They came with the data, but the data didn't come with an explanation.
